CXXFLAGS =	-O2 -g -Wall -fmessage-length=0

q1:
	$(CXX) -o q1 q1.cpp	

q2:
	$(CXX) -o q2 q2.cpp
	
q3:
	$(CXX) -o q3 q3.cpp	
		
q4:
	$(CXX) -o q4 q4.cpp	
	

all: clean q1 q2 q3 q4

clean: 
	rm -f q1 q2 q3 q4 *.o
